#!/bin/bash

source backup_params.sh

sleep_time=30
backup_time="0100"

justBackuped=false

echo "Starting backup daemon..."

while true; do
# Keep Daemon Running
	current_time=$(date +"%H%M")
	if [[ "$current_time" = "$backup_time" ]]; then
		# Time to backup!
		if [ "$justBackuped" = true ]; then
			continue
		fi

		./backup_now
		justBackuped=false
	fi
	sleep $sleep_time
done
